# Configure the database used when in the development environment
development:
  adapter: postgresql
  encoding: unicode
  database: dynamicare-challenge_development
  pool: 5
  username: postgres
  password: Asdfdsa123Car
  host: localhost

# Configure the database used when in the test environment
test:
  adapter: postgresql
  encoding: unicode
  database: dynamicare-challenge_test
  pool: 5
  username: postgres
  password: Asdfdsa123Car
  host: localhost

# Configure the database used when in the production environment
production:
  adapter: postgresql
  encoding: unicode
  database: dynamicare-challenge_production
  pool: 5
  username: postgres
  password: Asdfdsa123Car
  host: localhost
